export enum ItemType {
  Amulet = "Amulet",
  Belt = "Belt",
  BodyArmour = "Body Armour",
  Boots = "Boots",
  Bow = "Bow",
  Claw = "Claw",
  Dagger = "Dagger",
  Gloves = "Gloves",
  Helmet = "Helmet",
  Jewel = "Jewel",
  OneHandedAxe = "One Handed Axe",
  OneHandedMace = "One Handed Mace",
  OneHandedSword = "One Handed Sword",
  Quiver = "Quiver",
  Ring = "Ring",
  Shield = "Shield",
  Staff = "Staff",
  TwoHandedAxe = "Two Handed Axe",
  TwoHandedMace = "Two Handed Mace",
  TwoHandedSword = "Two Handed Sword",
  Wand = "Wand",
}
