export enum Variant {
  Crusader = "Crusader",
  CrusaderHunter = "Crusader/Hunter",
  CrusaderRedeemer = "Crusader/Redeemer",
  CrusaderWarlord = "Crusader/Warlord",
  Elder = "Elder",
  ElderCrusader = "Elder/Crusader",
  ElderHunter = "Elder/Hunter",
  ElderRedeemer = "Elder/Redeemer",
  ElderWarlord = "Elder/Warlord",
  Hunter = "Hunter",
  Redeemer = "Redeemer",
  RedeemerHunter = "Redeemer/Hunter",
  RedeemerWarlord = "Redeemer/Warlord",
  Shaper = "Shaper",
  ShaperCrusader = "Shaper/Crusader",
  ShaperElder = "Shaper/Elder",
  ShaperElderCrusaderRedeemerWarlordHunter = "Shaper/Elder/Crusader/Redeemer/Warlord/Hunter",
  ShaperHunter = "Shaper/Hunter",
  ShaperRedeemer = "Shaper/Redeemer",
  ShaperWarlord = "Shaper/Warlord",
  Warlord = "Warlord",
  WarlordHunter = "Warlord/Hunter",
}
