export enum Variant {
  Atlas = "Atlas",
  Atlas2 = "Atlas2",
  Atlas234 = "Atlas2-3.4",
  Blight = "Blight",
  Delerium = "Delerium",
  Gen11 = ", Gen-11",
  Gen12 = ", Gen-12",
  Gen13 = ", Gen-13",
  Gen14 = ", Gen-14",
  Gen15 = ", Gen-15",
  Gen16 = ", Gen-16",
  Harvest = "Harvest",
  Heist = "Heist",
  Legion = "Legion",
  Metamorph = "Metamorph",
  Pre20 = "Pre 2.0",
  Pre24 = "Pre 2.4",
  Ritual = "Ritual",
  Synthesis = "Synthesis",
}
