export enum BlightOil {
  ClearOil = "ClearOil",
  SepiaOil = "SepiaOil",
  AmberOil = "AmberOil",
  VerdantOil = "VerdantOil",
  TealOil = "TealOil",
  AzureOil = "AzureOil",
  IndigoOil = "IndigoOil",
  VioletOil = "VioletOil",
  CrimsonOil = "CrimsonOil",
  BlackOil = "BlackOil",
  OpalescentOil = "OpalescentOil",
  SilverOil = "SilverOil",
  GoldenOil = "GoldenOil",
  TaintedOil = "TaintedOil",
  ReflectiveOil = "ReflectiveOil",
}
