export enum InventoryId {
  Helm = "Helm",
  Weapon = "Weapon",
  Weapon2 = "Weapon2",
  Offhand = "Offhand",
  Offhand2 = "Offhand2",
  Amulet = "Amulet",
  Ring = "Ring",
  Ring2 = "Ring2",
  BodyArmour = "BodyArmour",
  Gloves = "Gloves",
  Belt = "Belt",
  Boots = "Boots",
  Flask = "Flask",
  MainInventory = "MainInventory",
  Trinket = "Trinket",
  PassiveJewels = "PassiveJewels",
}
