export enum BlightOil {
  ClearOil = "Clear Oil",
  SepiaOil = "Sepia Oil",
  AmberOil = "Amber Oil",
  VerdantOil = "Verdant Oil",
  TealOil = "Teal Oil",
  AzureOil = "Azure Oil",
  IndigoOil = "Indigo Oil",
  VioletOil = "Violet Oil",
  CrimsonOil = "Crimson Oil",
  BlackOil = "Black Oil",
  OpalescentOil = "Opalescent Oil",
  SilverOil = "Silver Oil",
  GoldenOil = "Golden Oil",
  TaintedOil = "Tainted Oil",
}
