name: Test

on: [push, pull_request]

jobs:
  pre_job:
    name: Check if skippable
    continue-on-error: true
    runs-on: ubuntu-latest

    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}

    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          concurrent_skipping: "same_content"

  test:
    name: Run Tests
    runs-on: ubuntu-latest

    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}

    steps:
      - name: Skip Duplicate Actions
        uses: fkirc/skip-duplicate-actions@v3.4.0

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"

      - name: Install modules
        run: npm ci

      - name: Run mocha tests
        env:
          POESESSID: ${{ secrets.POESESSID }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          SERVICE_TOKEN: ${{ secrets.SERVICE_TOKEN }}
          SCOPES: ${{ secrets.SCOPES }}
        run: env POESESSID=$POESESSID ACCESS_TOKEN=$ACCESS_TOKEN SERVICE_TOKEN=$SERVICE_TOKEN SCOPES="$SCOPES" npm run test:ci
